#language: c

sudo: required
dist: trusty

notifications:
  email: false

before_script:
  - sudo apt-get update
  - python3 --version
  - python2 --version
  - "sudo apt-get install -qq python-tk scons git || true"
  - "sudo pip install tensorflow keras matplotlib scikit-learn || true"

script:
  - export PYTHONPATH=`pwd`/scripts
  - cd examples/mnist-densenet && python model/mnist_densenet.py && cp -v weights.h mcu && scons

env:
  - NNOM_ON_CI=YES
