site_name: NNoM Documentation

theme:
  name: 'readthedocs'

repo_url: https://github.com/majianjia/nnom
site_description: 'A higher-level Neural Network library for microcontrollers.'

nav:
- Overview: 'index.md'
- Guides:
  - 5 min to NNoM: 'guide_5_min_to_nnom.md'
- APIs: 
  - Utils (Python): 'api_nnom_utils.md'
  - Model: 'api_model.md'
  - Construction: 'api_construction.md'
  - Properties: 'api_properties.md'
  - Core Layers: 'api_layers.md'
  - Pooling: 'api_pooling.md'
  - Activations: 'api_activations.md'
  - Merges: 'api_merge.md'
  - Evaluation: 'api_evaluation.md'
- Legacy Guide:
  - A Temporary Guide: 'A_Temporary_Guide_to_NNoM.md'
  - Porting and Optimisation Guide: 'Porting_and_Optimisation_Guide.md'
  - Old Readme: 'legacy_README.md'
- 中文: 
  - RT-Thread: 'rt-thread_guide.md'
  - MNIST-Simple: 'example_mnist_simple_cn.md'


